In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
import sys

# os.path.abspath("") lúc này là: ML-PROJECT/finetune_BERT
# os.path.join(..., "..") sẽ lùi lại 1 cấp để về: ML-PROJECT
project_root = os.path.abspath(os.path.join(os.path.abspath(""), ".."))

# Đổi hẳn thư mục làm việc (Working Directory) của cả file Notebook về ML-PROJECT
os.chdir(project_root)

# Thêm vào sys.path để sau này import các file .py khác nếu cần
if project_root not in sys.path:
    sys.path.append(project_root)

print(f"Thư mục làm việc hiện tại đã được đưa về: {os.getcwd()}")

Thư mục làm việc hiện tại đã được đưa về: /Users/user2/Documents/Github_Repos/ML-Project

In [4]:
df = pd.read_csv("data/train.csv")
# df_test = pd.read_csv('data/test.csv')

In [5]:
df.head()

,Unnamed: 0,paper_id,title,primary_category,authors,first_author,abstract,days_since_submission
0,0,cs-9308101v1,Dynamic Backtracking,cs.AI,M. L. Ginsberg,M. L. Ginsberg,Because of their occasional need to return to ...,12006
1,1,cs-9308102v1,A Market-Oriented Programming Environment and ...,cs.AI,M. P. Wellman,M. P. Wellman,Market price systems constitute a well-underst...,12006
2,2,cs-9309101v1,An Empirical Analysis of Search in GSAT,cs.AI,I. P. Gent; T. Walsh,I. P. Gent,We describe an extensive study of search in GS...,11975
3,3,cs-9311101v1,The Difficulties of Learning Logic Programs wi...,cs.AI,F. Bergadano; D. Gunetti; U. Trinchero,F. Bergadano,As real logic programmers normally use cut (!)...,11914
4,4,cs-9311102v1,Software Agents: Completing Patterns and Const...,cs.AI,J. C. Schlimmer; L. A. Hermens,J. C. Schlimmer,To support the goal of allowing users to recor...,11914

In [6]:
def add_content_col(df: pd.DataFrame) -> pd.DataFrame:
    content = df['title'] + " " + df['primary_category'] + " " + df['abstract']
    return pd.DataFrame({'paper_id': df['paper_id'], 'content': content})

In [7]:
content_df = add_content_col(df)

In [8]:
content_df.head()

       paper_id                                            content
0  cs-9308101v1  Dynamic Backtracking cs.AI Because of their oc...
1  cs-9308102v1  A Market-Oriented Programming Environment and ...
2  cs-9309101v1  An Empirical Analysis of Search in GSAT cs.AI ...
3  cs-9311101v1  The Difficulties of Learning Logic Programs wi...
4  cs-9311102v1  Software Agents: Completing Patterns and Const...

In [9]:
content_df.to_csv("finetune_BERT/train_content.csv")